/**
 * Negative parity for UnicodeMath: the port refuses what the gem refuses.
 *
 * The sibling of `test/formats/latex/rejection-parity.spec.ts`, for the same
 * reason. The positive corpus records only what the gem *produces*, so a port
 * that returns something plausible wherever the gem raises would pass it and
 * still be wrong.
 *
 * These cases come from the shared corpus (`plurimath-corpus/rejections/1`,
 * `corpus/unicode/rejections.yaml`), generated by sweeping candidate inputs
 * against the oracle and keeping the ones it refused. The corpus names the
 * format `unicode`, the gem's parse type, not `unicodemath`.
 *
 * On the recorded offset: `error.index` is an offset into `preprocessed`, not
 * into `input`. UnicodeMath's preprocessing turns every non-ASCII character
 * into a hexadecimal entity and strips the ends
 * (`src/formats/unicodemath/preprocess.ts`), so `α)` reaches the grammar as
 * `&#x3b1;)` and the offsets move. The port's own `ParseError.index` is an
 * offset into the ORIGINAL input (ARCHITECTURE.md §5), so the two are compared
 * through the `SourceMap` that pass returns.
 */

import { describe, expect, it } from "vitest";
import type { ParseError } from "../../../src/core/errors";
import { parseUnicodemath } from "../../../src/formats/unicodemath/parser";
import { preprocess } from "../../../src/formats/unicodemath/preprocess";
import { loadPinnedCorpus, type PinnedRejection } from "../../core/corpus-pin";
import { casesInInputFormat } from "../../core/model-builder";

const corpus = loadPinnedCorpus();

/**
 * The UnicodeMath rejections, selected on the case's own `input_format`
 * through the shared selector, which throws on an empty match: a pin that
 * drops `corpus/unicode/rejections.yaml` fails this file instead of running
 * zero cases.
 */
const rejections: readonly PinnedRejection[] = casesInInputFormat(corpus.rejections, "unicode");

describe("the UnicodeMath rejection corpus", () => {
  it("is not empty, asserted as a count", () => {
    expect(rejections.length).toBeGreaterThan(0);
    expect(rejections.length).toBe(52);
  });

  it("names every case exactly once", () => {
    expect(new Set(rejections.map((entry) => entry.id)).size).toBe(rejections.length);
  });

  it("is all UnicodeMath, and all one category", () => {
    for (const entry of rejections) {
      expect(entry.inputFormat, entry.id).toBe("unicode");
      expect(entry.category, entry.id).toBe("parse_error");
    }
  });
});

describe("every recorded UnicodeMath rejection is refused here too", () => {
  it.each(rejections.map((entry) => [entry.id, entry] as const))("%s", (_id, entry) => {
    let caught: unknown;
    try {
      parseUnicodemath(entry.input);
    } catch (error) {
      caught = error;
    }

    // The first assertion names the input when nothing was thrown — the
    // failure that matters is an input the gem refuses and this port ACCEPTS.
    expect(caught, `${entry.id}: ${JSON.stringify(entry.input)} was accepted`).toBeInstanceOf(
      Error,
    );
    // `code`, never `instanceof ParseError`: a dual ESM/CJS load can hold two
    // copies of these classes (ARCHITECTURE.md §5).
    expect((caught as ParseError).code, entry.id).toBe("PARSE_ERROR");
  });
});

/**
 * The cases where the port's failure position does not reproduce the gem's,
 * recorded rather than hidden. They share the cause the HTML and LaTeX suites
 * pin: the corpus records the furthest position any leaf of Parslet's failure
 * tree reached, while the port reports the first code unit its root rule could
 * not consume (`Atom#parse` in `src/pegkit/atom.ts`). Almost all are an
 * operator with nothing valid after it — the gem's offset is past the
 * operator, the port's is on it.
 *
 *   unicode-unclosed-paren-after-operator  `a+(b`   gem 4, port 2
 *   unicode-stray-close-square             `a]`     gem 2, port 1
 *   unicode-trailing-sup                   `a^`     gem 2, port 1
 *   unicode-greek-trailing-sup             `α^`     gem 2, port 1
 *   unicode-trailing-sub                   `a_`     gem 2, port 1
 *   unicode-infinity-trailing-sub          `∞_`     gem 2, port 1
 *   unicode-doubled-sup                    `a^^b`   gem 2, port 1
 *   unicode-doubled-sub                    `a__b`   gem 2, port 1
 *   unicode-sub-then-sup                   `a_^b`   gem 2, port 1
 *   unicode-trailing-slash                 `a/`     gem 2, port 1
 *   unicode-number-trailing-slash          `1/`     gem 2, port 1
 *   unicode-greek-trailing-slash           `α/`     gem 2, port 1
 *   unicode-double-trailing-slash          `a/b/`   gem 4, port 3
 *   unicode-ampersand-operator             `a&b`    gem 2, port 1
 *   unicode-greek-ampersand                `α&b`    gem 2, port 1
 *   unicode-trailing-down-tack             `a┬`     gem 2, port 1
 *   unicode-trailing-function-apply        `a⁡`     gem 2, port 1
 *   unicode-greek-function-apply           `α⁡`     gem 2, port 1
 *
 * (gem offsets already mapped back to the input; the last two inputs end in
 * U+2061 FUNCTION APPLICATION, which is invisible). Measured when this file
 * was written: the deepest position the port's own grammar TRIED
 * (`ctx.maxPos`) equals the recorded offset on 50 of the 52 cases, so the
 * grammar agrees with the gem's and, here, it is the reported metric that
 * differs. The metric is shared by every format and is not changed here; see
 * the HTML suite's note for why neither metric is the gem's.
 */
const KNOWN_POSITION_DIVERGENCES: readonly string[] = [
  "unicode-ampersand-operator",
  "unicode-double-trailing-slash",
  "unicode-doubled-sub",
  "unicode-doubled-sup",
  "unicode-greek-ampersand",
  "unicode-greek-function-apply",
  "unicode-greek-trailing-slash",
  "unicode-greek-trailing-sup",
  "unicode-infinity-trailing-sub",
  "unicode-number-trailing-slash",
  "unicode-stray-close-square",
  "unicode-sub-then-sup",
  "unicode-trailing-down-tack",
  "unicode-trailing-function-apply",
  "unicode-trailing-slash",
  "unicode-trailing-sub",
  "unicode-trailing-sup",
  "unicode-unclosed-paren-after-operator",
];

/** What the port actually reports, per case, measured against this pin. */
const PORT_INDEX: ReadonlyMap<string, number> = new Map([
  ["unicode-unclosed-paren", 2],
  ["unicode-stray-close-paren", 1],
  ["unicode-lone-close-paren", 0],
  ["unicode-close-paren-mid", 1],
  ["unicode-unclosed-paren-after-operator", 2],
  ["unicode-close-paren-after-operator", 2],
  ["unicode-unclosed-square", 2],
  ["unicode-stray-close-square", 1],
  ["unicode-unclosed-curly", 2],
  ["unicode-stray-close-curly", 1],
  ["unicode-unclosed-angle", 2],
  ["unicode-stray-close-angle", 1],
  ["unicode-unclosed-ceiling", 2],
  ["unicode-stray-close-ceiling", 1],
  ["unicode-unclosed-vert", 2],
  ["unicode-greek-stray-close-paren", 1],
  ["unicode-greek-unclosed-paren", 2],
  ["unicode-lone-sup", 1],
  ["unicode-trailing-sup", 1],
  ["unicode-greek-trailing-sup", 1],
  ["unicode-lone-sub", 1],
  ["unicode-trailing-sub", 1],
  ["unicode-infinity-trailing-sub", 1],
  ["unicode-doubled-sup", 1],
  ["unicode-doubled-sub", 1],
  ["unicode-sub-then-sup", 1],
  ["unicode-lone-slash", 1],
  ["unicode-trailing-slash", 1],
  ["unicode-number-trailing-slash", 1],
  ["unicode-leading-slash", 1],
  ["unicode-greek-trailing-slash", 1],
  ["unicode-double-trailing-slash", 3],
  ["unicode-lone-ampersand", 1],
  ["unicode-ampersand-operator", 1],
  ["unicode-greek-ampersand", 1],
  ["unicode-unclosed-quote", 4],
  ["unicode-greek-unclosed-quote", 4],
  ["unicode-matrix-unclosed", 5],
  ["unicode-lone-at", 0],
  ["unicode-at-operator", 1],
  ["unicode-greek-at-operator", 1],
  ["unicode-lone-naryand", 0],
  ["unicode-lone-right-tack", 0],
  ["unicode-trailing-down-tack", 1],
  ["unicode-lone-broken-bar", 0],
  ["unicode-trailing-broken-bar", 1],
  ["unicode-greek-broken-bar", 1],
  ["unicode-lone-function-apply", 1],
  ["unicode-trailing-function-apply", 1],
  ["unicode-greek-function-apply", 1],
  ["unicode-lone-parenthesized-letter", 1],
  ["unicode-whitespace-only", 1],
]);

describe("the port maps the UnicodeMath failure position back to the original input", () => {
  it("covers every recorded rejection, so a new case cannot skip the check", () => {
    expect([...PORT_INDEX.keys()].sort()).toStrictEqual(rejections.map((entry) => entry.id).sort());
  });

  it("reproduces the gem's preprocessing byte for byte", () => {
    // The comparison below maps the gem's offset through THIS port's source
    // map, which is only meaningful if both passes produced the same text.
    for (const entry of rejections) {
      expect(preprocess(entry.input).text, entry.id).toBe(entry.preprocessed);
    }
  });

  it("the counts this file names are derived, not recited", () => {
    const unshifted = rejections.filter((entry) => entry.input === entry.preprocessed);
    const shifted = rejections.filter((entry) => entry.input !== entry.preprocessed);
    expect(unshifted.length).toBe(28);
    expect(shifted.length).toBe(24);

    const diverging = rejections.filter(
      (entry) => mappedGemIndex(entry) !== PORT_INDEX.get(entry.id),
    );
    expect(diverging.map((entry) => entry.id).sort()).toStrictEqual([
      ...KNOWN_POSITION_DIVERGENCES,
    ]);
    expect(rejections.length - diverging.length).toBe(34);
  });

  it.each(rejections.map((entry) => [entry.id, entry] as const))(
    "%s: reports the measured original-input offset",
    (id, entry) => {
      let caught: unknown;
      try {
        parseUnicodemath(entry.input);
      } catch (error) {
        caught = error;
      }
      expect(caught, `${id} was accepted`).toBeInstanceOf(Error);
      expect((caught as ParseError).index, id).toBe(PORT_INDEX.get(id));
    },
  );

  it("reproduces the gem's recorded offset wherever the two agree", () => {
    const comparable = rejections.filter((entry) => !KNOWN_POSITION_DIVERGENCES.includes(entry.id));
    expect(comparable.length).toBe(34);
    for (const entry of comparable) {
      expect(PORT_INDEX.get(entry.id), entry.id).toBe(mappedGemIndex(entry));
    }
  });

  it("genuinely exercises the mapping, and does not merely restate the corpus", () => {
    // Without a case whose preprocessing changes length, every assertion above
    // is satisfied by a port that ignores its source map. Every shifted case
    // here changes length, and for each the mapped offset MOVED.
    const shifted = rejections.filter((entry) => entry.input !== entry.preprocessed);
    expect(shifted.length).toBeGreaterThan(0);
    for (const entry of shifted) {
      expect(mappedGemIndex(entry), entry.id).not.toBe(entry.index);
    }
  });
});

describe("the recorded offset describes the recorded text", () => {
  it("points inside `preprocessed`, which is what it is an offset into", () => {
    for (const entry of rejections) {
      if (entry.index === undefined) continue;
      expect(entry.index, entry.id).toBeGreaterThanOrEqual(0);
      expect(entry.index, entry.id).toBeLessThanOrEqual(entry.preprocessed.length);
    }
  });

  it("is present on every case, and not all zero", () => {
    const indices = rejections.map((entry) => entry.index);
    expect(indices.every((index) => index !== undefined)).toBe(true);
    expect(new Set(indices).size).toBeGreaterThan(1);
  });
});

/** The gem's recorded offset, carried into the original input's coordinates. */
function mappedGemIndex(entry: PinnedRejection): number {
  if (entry.index === undefined) throw new Error(`${entry.id} has no recorded index`);
  return preprocess(entry.input).map.toOriginal(entry.index);
}
