/**
 * The data `core` owns (`src/core/generated/`), against the census and against
 * the gem's own behaviour.
 *
 * Both tables exist for one reason — Ruby's `comparable_value` — and both are
 * generated by `scripts/generate-core-data.rb`. What the suite can check
 * without Ruby is that they are *complete* and *the right table*: every symbol
 * class the census knows has a canonical value or a recorded reason for having
 * none, and the entity set is the gem's `xhtml1` flavour rather than the
 * larger one a JavaScript library would bring.
 */

import { describe, expect, it } from "vitest";
import {
  XHTML1_ENTITY_CODEPOINTS,
  XHTML1_ENTITY_COUNT,
} from "../../src/core/generated/html-entities";
import { CORE_GENERATED_PROVENANCE } from "../../src/core/generated/provenance";
import {
  SYMBOL_CANONICAL_VALUES,
  SYMBOLS_WITHOUT_CANONICAL_VALUE,
} from "../../src/core/generated/symbol-canonical";
import { readCensus } from "./model-builder";

const SYMBOL_PREFIX = "Math::Symbols::";

describe("the xhtml1 entity table", () => {
  it("holds the flavour's full set, and no more", () => {
    expect(XHTML1_ENTITY_CODEPOINTS.size).toBe(XHTML1_ENTITY_COUNT);
    expect(XHTML1_ENTITY_COUNT).toBe(253);
  });

  it("is the gem's table, not the HTML5 one", () => {
    // `he` and `entities` decode both of these; `HTMLEntities` at its default
    // flavour does not, and that difference is why the table is generated.
    expect(XHTML1_ENTITY_CODEPOINTS.has("half")).toBe(false);
    expect(XHTML1_ENTITY_CODEPOINTS.has("sung")).toBe(false);
    // `apos` is what separates xhtml1 from html4, so it pins the flavour.
    expect(XHTML1_ENTITY_CODEPOINTS.get("apos")).toBe(39);
  });

  it("maps names to codepoints, spot-checked against the gem", () => {
    expect(XHTML1_ENTITY_CODEPOINTS.get("amp")).toBe(38);
    expect(XHTML1_ENTITY_CODEPOINTS.get("pi")).toBe(960);
    expect(XHTML1_ENTITY_CODEPOINTS.get("Pi")).toBe(928);
    expect(XHTML1_ENTITY_CODEPOINTS.get("frac12")).toBe(189);
    expect(XHTML1_ENTITY_CODEPOINTS.get("times")).toBe(215);
  });

  it("keeps every name inside the shape the decoder's pattern assumes", () => {
    // Ruby builds `[a-z][a-z0-9]{min-1,max-1}` from the table's own key
    // lengths. Our pattern drops the bounds, which is only safe while no key
    // is one character long — a one-character key would then decode where the
    // gem's would not.
    for (const name of XHTML1_ENTITY_CODEPOINTS.keys()) {
      expect(name, name).toMatch(/^[A-Za-z][A-Za-z0-9]*$/);
      expect(name.length, name).toBeGreaterThanOrEqual(2);
      expect(name.length, name).toBeLessThanOrEqual(8);
    }
  });

  it("holds only codepoints a string can carry", () => {
    for (const [name, codepoint] of XHTML1_ENTITY_CODEPOINTS) {
      expect(Number.isInteger(codepoint), name).toBe(true);
      expect(codepoint, name).toBeGreaterThan(0);
      expect(codepoint, name).toBeLessThanOrEqual(0xffff);
    }
  });
});

describe("the canonical symbol values", () => {
  const census = readCensus();
  const symbolIds = census.classes
    .filter((entry) => entry.name.startsWith(SYMBOL_PREFIX))
    .map((entry) => entry.name.slice(SYMBOL_PREFIX.length));

  it("covers every symbol class the census knows, once", () => {
    expect(symbolIds.length).toBeGreaterThan(1400);
    const covered = [...SYMBOL_CANONICAL_VALUES.keys(), ...SYMBOLS_WITHOUT_CANONICAL_VALUE];
    expect([...covered].sort()).toStrictEqual([...symbolIds].sort());
    expect(new Set(covered).size).toBe(covered.length);
  });

  it("records the two classes Ruby gives no fallback, and only those", () => {
    // `Symbol` short-circuits on `instance_of?(Symbol)`; `Paren` is the
    // abstract root, whose inherited `to_unicodemath` returns its nil value.
    expect([...SYMBOLS_WITHOUT_CANONICAL_VALUE]).toStrictEqual(["Paren", "Symbol"]);
    for (const id of SYMBOLS_WITHOUT_CANONICAL_VALUE) {
      expect(SYMBOL_CANONICAL_VALUES.has(id), id).toBe(false);
    }
  });

  it("carries the values the gem renders, spot-checked", () => {
    expect(SYMBOL_CANONICAL_VALUES.get("Plus")).toBe("+");
    expect(SYMBOL_CANONICAL_VALUES.get("Pi")).toBe("π");
    expect(SYMBOL_CANONICAL_VALUES.get("Comma")).toBe(",");
    // Two classes, one character: `id` is what keeps them unequal.
    expect(SYMBOL_CANONICAL_VALUES.get("Lparen")).toBe("(");
    expect(SYMBOL_CANONICAL_VALUES.get("Paren::Lround")).toBe("(");
  });

  it("holds no empty value, which would be indistinguishable from no value", () => {
    for (const [id, value] of SYMBOL_CANONICAL_VALUES) {
      expect(value.length, id).toBeGreaterThan(0);
    }
  });
});

describe("core's generated provenance", () => {
  it("names the oracle and the entity library the tables came from", () => {
    expect(CORE_GENERATED_PROVENANCE.generator).toBe("scripts/generate-core-data.rb");
    expect(CORE_GENERATED_PROVENANCE.oracle).toBe("plurimath");
    expect(CORE_GENERATED_PROVENANCE.oracleCommit).toMatch(/^[0-9a-f]{40}$/);
    // The flavour is the whole argument for generating rather than importing.
    expect(CORE_GENERATED_PROVENANCE.entityLibrary).toBe("htmlentities");
    expect(CORE_GENERATED_PROVENANCE.entityFlavour).toBe("xhtml1");
  });

  it("hashes every generator input, not only the entry point", () => {
    // The generator borrows class discovery, symbol ids and hashing from the
    // corpus generator, so a change there moves these tables. Hashing only the
    // script that was run would let that happen with the provenance unchanged.
    const inputs = CORE_GENERATED_PROVENANCE.generatorInputs;
    expect(inputs.get("scripts/generate-core-data.rb")).toMatch(/^[0-9a-f]{64}$/);
    expect(inputs.get("scripts/generate-corpus.rb")).toMatch(/^[0-9a-f]{64}$/);
    // The entry point is one of the inputs, and every input is a real script.
    expect(inputs.has(CORE_GENERATED_PROVENANCE.generator)).toBe(true);
    for (const [path, hash] of inputs) {
      expect(path, path).toMatch(/^scripts\/[\w.-]+\.rb$/);
      expect(hash, path).toMatch(/^[0-9a-f]{64}$/);
    }
  });

  it("was generated from clean checkouts, so the tables may be committed", () => {
    // §7: `--allow-dirty` output is marked non-committable and CI rejects it.
    // This is the assertion that makes "CI rejects it" true rather than a
    // claim — it fails until the tables are regenerated from a clean tree.
    expect(CORE_GENERATED_PROVENANCE.oracleClean).toBe(true);
    expect(CORE_GENERATED_PROVENANCE.generatorClean).toBe(true);
    expect(CORE_GENERATED_PROVENANCE.committable).toBe(true);
  });
});
