/**
 * Negative parity for HTML: the port refuses what the gem refuses.
 *
 * The sibling of `test/formats/latex/rejection-parity.spec.ts`, for the same
 * reason. The positive corpus records only what the gem *produces*, so a port
 * that returns something plausible wherever the gem raises would pass it and
 * still be wrong.
 *
 * These cases come from the shared corpus (`plurimath-corpus/rejections/1`,
 * `corpus/html/rejections.yaml`), generated by sweeping candidate inputs
 * against the oracle and keeping the ones it refused. HTML has no positive
 * payload in the pin, only this one.
 *
 * On the recorded offset: `error.index` is an offset into `preprocessed`, not
 * into `input`. HTML's preprocessing rewrites every entity to its hexadecimal
 * spelling (`src/formats/html/preprocess.ts`), which moves later offsets
 * whenever the two spellings differ in length. The port's own
 * `ParseError.index` is an offset into the ORIGINAL input (ARCHITECTURE.md §5),
 * so the two are compared through the `SourceMap` that pass returns.
 */

import { describe, expect, it } from "vitest";
import type { ParseError } from "../../../src/core/errors";
import { parseHtml } from "../../../src/formats/html/parser";
import { preprocess } from "../../../src/formats/html/preprocess";
import { loadPinnedCorpus, type PinnedRejection } from "../../core/corpus-pin";
import { casesInInputFormat } from "../../core/model-builder";

const corpus = loadPinnedCorpus();

/**
 * The HTML rejections, selected on the case's own `input_format` through the
 * shared selector, which throws on an empty match: a pin that drops
 * `corpus/html/rejections.yaml` fails this file instead of running zero cases.
 */
const rejections: readonly PinnedRejection[] = casesInInputFormat(corpus.rejections, "html");

/** The case the gem refuses AFTER its grammar succeeded, so it records no offset. */
const NO_GRAMMAR_OFFSET = "html-nesting-too-deep";

describe("the HTML rejection corpus", () => {
  it("is not empty, asserted as a count", () => {
    expect(rejections.length).toBeGreaterThan(0);
    expect(rejections.length).toBe(38);
  });

  it("names every case exactly once", () => {
    expect(new Set(rejections.map((entry) => entry.id)).size).toBe(rejections.length);
  });

  it("is all HTML, and all one category", () => {
    for (const entry of rejections) {
      expect(entry.inputFormat, entry.id).toBe("html");
      expect(entry.category, entry.id).toBe("parse_error");
    }
  });
});

describe("every recorded HTML rejection is refused here too", () => {
  it.each(rejections.map((entry) => [entry.id, entry] as const))("%s", (_id, entry) => {
    let caught: unknown;
    try {
      parseHtml(entry.input);
    } catch (error) {
      caught = error;
    }

    // The first assertion names the input when nothing was thrown — the
    // failure that matters is an input the gem refuses and this port ACCEPTS.
    expect(caught, `${entry.id}: ${JSON.stringify(entry.input)} was accepted`).toBeInstanceOf(
      Error,
    );
    // `code`, never `instanceof ParseError`: a dual ESM/CJS load can hold two
    // copies of these classes (ARCHITECTURE.md §5).
    expect((caught as ParseError).code, entry.id).toBe("PARSE_ERROR");
  });
});

/**
 * The cases where the port's failure position does not reproduce the gem's,
 * recorded rather than hidden. They share one cause, the one the LaTeX suite
 * pins for `latex-right-without-left`: the two sides measure different things.
 * The corpus records the furthest position any leaf of Parslet's failure tree
 * reached, while the port reports the first code unit its root rule could not
 * consume (`Atom#parse` in `src/pegkit/atom.ts`). Where the grammar gave up
 * after trying something past the last consumed character, the two differ.
 *
 *   html-extra-close-tag               `<i>a</i></i>`     gem 9,  port 8
 *   html-lt-between-letters            `a<b`              gem 3,  port 1
 *   html-sup-without-close             `2<sup>`           gem 6,  port 1
 *   html-empty-sup                     `2<sup></sup>`     gem 7,  port 1
 *   html-function-unclosed-paren       `sqrt(`            gem 5,  port 4
 *   html-entity-then-lone-sub          `&alpha;<sub>`     gem 12, port 7
 *   html-entity-sum-then-lone-sub      `&sum;<sub>`       gem 10, port 5
 *   html-numeric-entity-then-sup       `&#x3b1;<sup>`     gem 12, port 7
 *   html-entity-then-open-tag          `&infin;<i>`       gem 10, port 7
 *   html-entity-then-mismatched-close  `&alpha;<i>a</b>`  gem 13, port 7
 *
 * (gem offsets already mapped back to the input). Measured when this file was
 * written: the deepest position the port's own grammar TRIED (`ctx.maxPos`)
 * equals the recorded offset on all 37 HTML cases that carry one, so the
 * grammar agrees with the gem's and only the reported metric differs. It is
 * not changed here because the metric is shared by every format: measured the
 * same way, reporting `maxPos` would also fix LaTeX's two pinned cases, but
 * would break 6 of the 12 AsciiMath rejections that agree today, so neither
 * metric is the gem's and matching it needs Parslet's failure tree modelled.
 */
const KNOWN_POSITION_DIVERGENCES: readonly string[] = [
  "html-empty-sup",
  "html-entity-sum-then-lone-sub",
  "html-entity-then-lone-sub",
  "html-entity-then-mismatched-close",
  "html-entity-then-open-tag",
  "html-extra-close-tag",
  "html-function-unclosed-paren",
  "html-lt-between-letters",
  "html-numeric-entity-then-sup",
  "html-sup-without-close",
];

/** What the port actually reports, per case, measured against this pin. */
const PORT_INDEX: ReadonlyMap<string, number> = new Map([
  ["html-unclosed-tag", 4],
  ["html-stray-close-tag", 1],
  ["html-stray-close-then-text", 1],
  ["html-extra-close-tag", 8],
  ["html-mismatched-close", 6],
  ["html-crossed-tags", 9],
  ["html-empty-element", 4],
  ["html-empty-tag-name", 1],
  ["html-unterminated-tag", 2],
  ["html-unclosed-var", 5],
  ["html-comment", 1],
  ["html-lone-lt", 1],
  ["html-lone-gt", 0],
  ["html-lt-between-letters", 1],
  ["html-gt-between-letters", 1],
  ["html-lone-sub", 5],
  ["html-unclosed-sub", 6],
  ["html-sup-without-close", 1],
  ["html-empty-sup", 1],
  ["html-unclosed-paren", 2],
  ["html-unclosed-paren-space", 3],
  ["html-stray-close-paren", 1],
  ["html-stray-close-paren-space", 2],
  ["html-function-unclosed-paren", 4],
  ["html-unclosed-table", 7],
  ["html-empty-table", 8],
  ["html-empty-row", 12],
  ["html-table-without-close", 26],
  ["html-entity-then-lone-sub", 7],
  ["html-entity-sum-then-lone-sub", 5],
  ["html-numeric-entity-then-sup", 7],
  ["html-entity-then-close-paren", 7],
  ["html-paren-then-entity", 8],
  ["html-entity-then-open-tag", 7],
  ["html-entity-then-mismatched-close", 7],
  ["html-unclosed-tag-around-entity", 10],
  ["html-table-without-close-entity", 32],
  // No grammar offset exists on the gem's side (see NO_GRAMMAR_OFFSET); the
  // port attributes a failure from past the grammar to offset 0 (`parseHtml`).
  ["html-nesting-too-deep", 0],
]);

describe("the port maps the HTML failure position back to the original input", () => {
  it("covers every recorded rejection, so a new case cannot skip the check", () => {
    expect([...PORT_INDEX.keys()].sort()).toStrictEqual(rejections.map((entry) => entry.id).sort());
  });

  it("reproduces the gem's preprocessing byte for byte", () => {
    // The comparison below maps the gem's offset through THIS port's source
    // map, which is only meaningful if both passes produced the same text.
    for (const entry of rejections) {
      expect(preprocess(entry.input).text, entry.id).toBe(entry.preprocessed);
    }
  });

  it("records no offset for exactly the refusal that happens past the grammar", () => {
    const unindexed = rejections.filter((entry) => entry.index === undefined);
    expect(unindexed.map((entry) => entry.id)).toStrictEqual([NO_GRAMMAR_OFFSET]);
  });

  it("the counts this file names are derived, not recited", () => {
    const indexed = rejections.filter((entry) => entry.index !== undefined);
    const shifted = rejections.filter((entry) => entry.input !== entry.preprocessed);
    expect(indexed.length).toBe(37);
    expect(shifted.length).toBe(8);

    const diverging = indexed.filter((entry) => mappedGemIndex(entry) !== PORT_INDEX.get(entry.id));
    expect(diverging.map((entry) => entry.id).sort()).toStrictEqual([
      ...KNOWN_POSITION_DIVERGENCES,
    ]);
    expect(indexed.length - diverging.length).toBe(27);
  });

  it.each(rejections.map((entry) => [entry.id, entry] as const))(
    "%s: reports the measured original-input offset",
    (id, entry) => {
      let caught: unknown;
      try {
        parseHtml(entry.input);
      } catch (error) {
        caught = error;
      }
      expect(caught, `${id} was accepted`).toBeInstanceOf(Error);
      expect((caught as ParseError).index, id).toBe(PORT_INDEX.get(id));
    },
  );

  it("reproduces the gem's recorded offset wherever the two agree", () => {
    const comparable = rejections.filter(
      (entry) => entry.index !== undefined && !KNOWN_POSITION_DIVERGENCES.includes(entry.id),
    );
    expect(comparable.length).toBe(27);
    for (const entry of comparable) {
      expect(PORT_INDEX.get(entry.id), entry.id).toBe(mappedGemIndex(entry));
    }
  });

  it("genuinely exercises the mapping, and does not merely restate the corpus", () => {
    // Most HTML entities keep their length under the rewrite (`&alpha;` and
    // `&#x3b1;` are both seven characters), so a changed text alone does not
    // prove an offset moved. These are the cases where the mapped offset DID
    // move; without them, a port ignoring its source map would pass.
    const moved = rejections.filter(
      (entry) => entry.index !== undefined && mappedGemIndex(entry) !== entry.index,
    );
    expect(moved.map((entry) => entry.id).sort()).toStrictEqual([
      "html-entity-sum-then-lone-sub",
      "html-entity-then-open-tag",
    ]);
  });
});

describe("the recorded offset describes the recorded text", () => {
  it("points inside `preprocessed`, which is what it is an offset into", () => {
    for (const entry of rejections) {
      if (entry.index === undefined) continue;
      expect(entry.index, entry.id).toBeGreaterThanOrEqual(0);
      expect(entry.index, entry.id).toBeLessThanOrEqual(entry.preprocessed.length);
    }
  });

  it("is not all one value", () => {
    const indices = rejections.map((entry) => entry.index).filter((index) => index !== undefined);
    expect(new Set(indices).size).toBeGreaterThan(1);
  });
});

/** The gem's recorded offset, carried into the original input's coordinates. */
function mappedGemIndex(entry: PinnedRejection): number {
  if (entry.index === undefined) throw new Error(`${entry.id} has no recorded index`);
  return preprocess(entry.input).map.toOriginal(entry.index);
}
