/**
 * The gem-verified MathML render sweep: the SAME 1,642 inputs as the
 * asciimath sweep (test/formats/asciimath/render-sweep.json — curated
 * constructs, one plain token per symbol id, the quoted wrapper forms), each
 * re-rendered through the ORACLE's `to_mathml` with default options
 * (`Plurimath::Math.parse(input, :asciimath).to_mathml` on the pinned
 * checkout, plurimath 0.11.6 at 00c52783, 2026-08-10 — probe
 * mathml-sweep.rb), and recorded as either the gem's exact bytes or its
 * refusal. This port must reproduce every pair.
 *
 * Six refusals are data, not test bugs: `x/` fails to PARSE, while `""`,
 * `" "`, `textbf x`, `textit x` and `textrm x` parse and then fail to
 * RENDER — the same six the asciimath sweep pins, because the crashes live
 * in the shared parse output (a bare string in a formula's value, a `Text`
 * holding a Symbol), not in either serializer.
 *
 * The fixture is one-off generated, not regenerated by `scripts/`: it
 * records oracle answers that only change when the pinned oracle moves.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { ParseError, RenderError } from "../../../src/core/errors";
import { parseAsciimath } from "../../../src/formats/asciimath/parser";
import { toMathml } from "../../../src/formats/mathml/renderer";

interface SweepCase {
  readonly input: string;
  readonly render?: string;
  readonly error?: "parse" | "render";
  readonly errorClass?: string;
}

interface SweepFixture {
  readonly description: string;
  readonly oracle: { readonly version: string; readonly commit: string };
  readonly count: number;
  readonly cases: readonly SweepCase[];
}

const fixturePath = join(dirname(fileURLToPath(import.meta.url)), "render-sweep.json");
const fixture = JSON.parse(readFileSync(fixturePath, "utf8")) as SweepFixture;

describe("the gem-verified mathml render sweep", () => {
  it("is complete and non-empty (an empty sweep is a failure, not a pass)", () => {
    expect(fixture.cases.length).toBe(1642);
    expect(fixture.cases.length).toBe(fixture.count);
    expect(fixture.oracle.commit).toBe("00c52783877b38f6b8e6e109f1803f96bb34fc62");
    for (const entry of fixture.cases) {
      expect(typeof entry.input, JSON.stringify(entry)).toBe("string");
      expect(entry.render !== undefined || entry.error !== undefined).toBe(true);
      expect(entry.render !== undefined && entry.error !== undefined).toBe(false);
    }
  });

  // 30s, not the 5s default. This walks the whole recorded sweep — thousands
  // of parses and renders — and lands within a few hundred milliseconds of the
  // default when the suite runs it alongside everything else, so it passed
  // alone and failed in a full run. A timeout that depends on machine load is
  // a flaky gate, and a flaky gate gets ignored.
  it("reproduces every gem render byte for byte", () => {
    const rendered = fixture.cases.filter((entry) => entry.render !== undefined);
    expect(rendered.length).toBeGreaterThan(0);
    const divergences: string[] = [];
    for (const entry of rendered) {
      let actual: string;
      try {
        actual = toMathml(parseAsciimath(entry.input));
      } catch (error) {
        divergences.push(`${JSON.stringify(entry.input)}: threw ${String(error)}`);
        continue;
      }
      if (actual !== entry.render) {
        divergences.push(
          `${JSON.stringify(entry.input)}: rendered ${JSON.stringify(actual)}, gem says ${JSON.stringify(entry.render)}`,
        );
      }
    }
    expect(divergences).toEqual([]);
    expect(rendered.length).toBe(1636);
  }, 30_000);

  it("refuses to parse exactly what the gem refuses to parse", () => {
    const refused = fixture.cases.filter((entry) => entry.error === "parse");
    expect(refused.length).toBe(1);
    for (const entry of refused) {
      expect(() => parseAsciimath(entry.input), JSON.stringify(entry.input)).toThrow(ParseError);
    }
  });

  it("raises RenderError exactly where the gem's render raises", () => {
    const refused = fixture.cases.filter((entry) => entry.error === "render");
    expect(refused.length).toBe(5);
    for (const entry of refused) {
      const formula = parseAsciimath(entry.input); // the gem parses these too
      expect(() => toMathml(formula), JSON.stringify(entry.input)).toThrow(RenderError);
    }
  });
});
