/**
 * Negative parity: the port refuses what the gem refuses.
 *
 * The positive corpus records only what the gem *produces*, so a port that
 * returns something plausible wherever the gem raises passes every case in it
 * and is still wrong. These cases come from the same shared corpus
 * (`plurimath-corpus/rejections/1`), generated by sweeping a committed list of
 * candidate inputs against the oracle and keeping the ones it refused.
 *
 * `test/formats/asciimath/failure-parity.spec.ts` is the in-repo half of this:
 * a 156-candidate sweep with its own tables, plus the 4,368-input structural
 * sweep that showed no case where the gem rejects and this port accepts. What
 * this file adds is the *shared* half — the same inputs every implementation
 * checks, so the ports agree with each other and not merely each with the gem.
 *
 * On the recorded offset: `error.index` is an offset into `preprocessed`, not
 * into `input`, because AsciiMath's parser rewrites `{:` and friends to single
 * characters before parsing and every later offset shifts. The port's own
 * `ParseError.index` is an offset into the ORIGINAL input (ARCHITECTURE.md §5),
 * so the two are only comparable through an offset map. Until that mapping is
 * pinned, this file asserts the *refusal*, and asserts the index is a position
 * inside the recorded text rather than pretending to compare it.
 */

import { describe, expect, it } from "vitest";
import { ParseError } from "../../../src/core/errors";
import { parseAsciimath } from "../../../src/formats/asciimath/parser";
import { loadPinnedCorpus, type PinnedRejection } from "../../core/corpus-pin";

const corpus = loadPinnedCorpus();
const rejections: readonly PinnedRejection[] = corpus.rejections;

describe("the rejection corpus", () => {
  it("is not empty, asserted as a count", () => {
    // A rejection suite that runs zero cases passes in silence, and this
    // repository has already shipped one gate that did exactly that.
    expect(rejections.length).toBeGreaterThan(0);
    expect(rejections.length).toBe(7);
  });

  it("names every case exactly once", () => {
    expect(new Set(rejections.map((entry) => entry.id)).size).toBe(rejections.length);
  });

  it("is all AsciiMath, and all one category", () => {
    for (const entry of rejections) {
      expect(entry.inputFormat, entry.id).toBe("asciimath");
      expect(entry.category, entry.id).toBe("parse_error");
    }
  });

  it("carries the two incomplete-fraction cases the plan requires by name", () => {
    // TODO 8 names `a/` and `/b` specifically: they are the only class the
    // measured sweep found the gem rejecting at all.
    const inputs = rejections.map((entry) => entry.input);
    expect(inputs).toContain("a/");
    expect(inputs).toContain("/b");
  });
});

describe("every recorded rejection is refused here too", () => {
  it.each(rejections.map((entry) => [entry.id, entry] as const))("%s", (_id, entry) => {
    let caught: unknown;
    try {
      parseAsciimath(entry.input);
    } catch (error) {
      caught = error;
    }

    expect(caught, `${entry.id}: ${JSON.stringify(entry.input)} was accepted`).toBeInstanceOf(
      ParseError,
    );
    // The code, not just the class: ARCHITECTURE.md §5 makes `code` the
    // guaranteed discriminator, because a dual ESM/CJS load can hold two
    // copies of these classes and `instanceof` across copies is false.
    expect((caught as ParseError).code).toBe("PARSE_ERROR");
  });

  it("the suite fails when pointed at an empty set", () => {
    // Demonstrated, not assumed. The assertion above is `it.each` over the
    // corpus, so an empty corpus would run zero cases and report success; this
    // is the guard that makes that impossible, proven by running it.
    const empty: readonly PinnedRejection[] = [];
    expect(() => {
      expect(empty.length).toBeGreaterThan(0);
    }).toThrow();
  });
});

describe("the recorded offset describes the recorded text", () => {
  it("points inside `preprocessed`, which is what it is an offset into", () => {
    for (const entry of rejections) {
      if (entry.index === undefined) continue;
      expect(entry.index, entry.id).toBeGreaterThanOrEqual(0);
      expect(entry.index, entry.id).toBeLessThanOrEqual(entry.preprocessed.length);
    }
  });

  it("is present on every case, and not all zero", () => {
    // All-zero would be the signature of reading Parslet's root failure
    // position, which is 0 for every rejection whatever went wrong deeper in.
    const indices = rejections.map((entry) => entry.index);
    expect(indices.every((index) => index !== undefined)).toBe(true);
    expect(new Set(indices).size).toBeGreaterThan(1);
  });
});
