/**
 * Negative parity: the port refuses what the gem refuses.
 *
 * The positive corpus records only what the gem *produces*, so a port that
 * returns something plausible wherever the gem raises passes every case in it
 * and is still wrong. These cases come from the same shared corpus
 * (`plurimath-corpus/rejections/1`), generated by sweeping a committed list of
 * candidate inputs against the oracle and keeping the ones it refused.
 *
 * `test/formats/asciimath/failure-parity.spec.ts` is the in-repo half of this:
 * a 156-candidate sweep with its own tables, plus the 4,368-input structural
 * sweep that showed no case where the gem rejects and this port accepts. What
 * this file adds is the *shared* half — the same inputs every implementation
 * checks, so the ports agree with each other and not merely each with the gem.
 *
 * On the recorded offset: `error.index` is an offset into `preprocessed`, not
 * into `input`, because AsciiMath's parser rewrites `{:` and friends to single
 * characters before parsing and every later offset shifts. The port's own
 * `ParseError.index` is an offset into the ORIGINAL input (ARCHITECTURE.md §5),
 * so the two are comparable only through an offset map.
 *
 * That comparison used to be postponed, and postponing it made this gate blind
 * in two ways at once: nothing here would have failed if the port stopped
 * mapping offsets entirely, and every rejection case then recorded had `input`
 * identical to `preprocessed`, so no case could have told the difference. Four
 * cases whose preprocessing CHANGES LENGTH now exist for exactly this
 * (`{:a:}(:b:)c/` is 12 characters and preprocesses to 8), and the mapped
 * index is asserted per case below.
 */

import { describe, expect, it } from "vitest";
import type { ParseError } from "../../../src/core/errors";
import { parseAsciimath } from "../../../src/formats/asciimath/parser";
import { loadPinnedCorpus, type PinnedRejection } from "../../core/corpus-pin";

const corpus = loadPinnedCorpus();
const rejections: readonly PinnedRejection[] = corpus.rejections;

describe("the rejection corpus", () => {
  it("is not empty, asserted as a count", () => {
    // A rejection suite that runs zero cases passes in silence, and this
    // repository has already shipped one gate that did exactly that.
    expect(rejections.length).toBeGreaterThan(0);
    expect(rejections.length).toBe(13);
  });

  it("names every case exactly once", () => {
    expect(new Set(rejections.map((entry) => entry.id)).size).toBe(rejections.length);
  });

  it("is all AsciiMath, and all one category", () => {
    for (const entry of rejections) {
      expect(entry.inputFormat, entry.id).toBe("asciimath");
      expect(entry.category, entry.id).toBe("parse_error");
    }
  });

  it("carries the two incomplete-fraction cases the plan requires by name", () => {
    // TODO 8 names `a/` and `/b` specifically. They are the LARGEST class the
    // measured sweep found the gem rejecting, not the only one: a lone
    // backtick, a lone `right`, and a `left(` group whose `right` has no
    // closing paren are rejected too, and four brace-prefixed fraction shapes
    // were added later for their shifted offsets.
    const inputs = rejections.map((entry) => entry.input);
    expect(inputs).toContain("a/");
    expect(inputs).toContain("/b");
  });
});

describe("every recorded rejection is refused here too", () => {
  it.each(rejections.map((entry) => [entry.id, entry] as const))("%s", (_id, entry) => {
    let caught: unknown;
    try {
      parseAsciimath(entry.input);
    } catch (error) {
      caught = error;
    }

    // Two assertions doing two different jobs. The first only has to prove
    // something was thrown, and names the input when nothing was — the failure
    // that matters here is an input the gem refuses and this port ACCEPTS.
    // `Error` is the global, so this holds even under a dual ESM/CJS load.
    expect(caught, `${entry.id}: ${JSON.stringify(entry.input)} was accepted`).toBeInstanceOf(
      Error,
    );
    // The discrimination is `code`, never `instanceof ParseError`: ARCHITECTURE.md
    // §5 makes `code` the guaranteed discriminator precisely because a dual
    // ESM/CJS load can hold two copies of these classes, and `instanceof`
    // across copies is false. Asserting the class here would have contradicted
    // the reason given for asserting the code.
    expect((caught as ParseError).code).toBe("PARSE_ERROR");
  });

  it("the suite fails when pointed at an empty set", () => {
    // Demonstrated, not assumed. The assertion above is `it.each` over the
    // corpus, so an empty corpus would run zero cases and report success; this
    // is the guard that makes that impossible, proven by running it.
    const empty: readonly PinnedRejection[] = [];
    expect(() => {
      expect(empty.length).toBeGreaterThan(0);
    }).toThrow();
  });
});

/**
 * The port's `ParseError.index` per case, measured against this pin.
 *
 * Eight of the nine unshifted cases reproduce the gem's recorded offset
 * exactly, and all four shifted cases map back to the right position in the
 * ORIGINAL input. Those counts are checked rather than merely stated: "the
 * counts this header names are derived, not recited" below computes all three
 * from the corpus and this map, so a rejection case added to the pin fails
 * there instead of ageing this paragraph. One case does not reproduce the
 * gem's offset, and is recorded rather than hidden:
 *
 *   right-unclosed  `left( x right`  gem 13 (end of input), port 8 (at `right`)
 *
 * Both are defensible readings of "where it failed" — Parslet reports the
 * furthest position it reached after consuming everything, the port reports
 * where the unsatisfiable construct began — but they are not the same number,
 * and PORTING-STANDARDS.md makes the gem's the specification. It is pinned
 * here as a KNOWN DIVERGENCE with its measured values so it cannot drift
 * further unnoticed, and TODO.plan carries the decision about closing it.
 * Asserting agreement here would be false; asserting nothing hid it entirely.
 */
const MAPPED_INDEX: ReadonlyMap<string, number> = new Map([
  ["frac-trailing", 1],
  ["frac-leading", 0],
  ["frac-bare", 0],
  ["frac-trailing-space", 2],
  ["backtick-bare", 0],
  ["right-without-left", 0],
  ["right-unclosed", 8],
  ["frac-trailing-after-brace", 3],
  ["frac-trailing-after-braces", 6],
  ["frac-trailing-after-parens", 6],
  ["frac-trailing-after-both", 11],
  // The widened corpus's two explicit-fence rejections. The gem records 8 for
  // both and the port reports 8 for both, so these agree — unlike
  // `right-unclosed`, whose disagreement is pinned below.
  ["left-right-curly", 8],
  ["left-right-vert", 8],
]);

/** The one case whose mapped index does not reproduce the gem's. */
const KNOWN_POSITION_DIVERGENCE = "right-unclosed";

describe("the port maps the failure position back to the original input", () => {
  it("covers every recorded rejection, so a new case cannot skip the check", () => {
    expect([...MAPPED_INDEX.keys()].sort()).toStrictEqual(
      rejections.map((entry) => entry.id).sort(),
    );
  });

  it("the counts this header names are derived, not recited", () => {
    // 9 unshifted / 4 shifted / 8 of the 9 agreeing, computed from the corpus
    // and MAPPED_INDEX rather than restated from the paragraph above. On this
    // pin, `right-unclosed` is the only unshifted case where the two numbers
    // differ (gem 13, port 8); every shifted case differs from its recorded
    // offset by construction, because the recorded one indexes `preprocessed`.
    const unshifted = rejections.filter((entry) => entry.input === entry.preprocessed);
    const shifted = rejections.filter((entry) => entry.input !== entry.preprocessed);
    expect(unshifted.length).toBe(9);
    expect(shifted.length).toBe(4);

    const agreeing = unshifted.filter((entry) => MAPPED_INDEX.get(entry.id) === entry.index);
    expect(agreeing.length).toBe(8);
    expect(
      unshifted
        .filter((entry) => MAPPED_INDEX.get(entry.id) !== entry.index)
        .map((entry) => entry.id),
    ).toStrictEqual([KNOWN_POSITION_DIVERGENCE]);
  });

  it.each(rejections.map((entry) => [entry.id, entry] as const))(
    "%s: reports the measured original-input offset",
    (id, entry) => {
      let caught: unknown;
      try {
        parseAsciimath(entry.input);
      } catch (error) {
        caught = error;
      }
      expect(caught, `${id} was accepted`).toBeInstanceOf(Error);
      expect((caught as ParseError).index, id).toBe(MAPPED_INDEX.get(id));
    },
  );

  it("reproduces the gem's recorded offset wherever the two agree", () => {
    // The UNSHIFTED cases only, which is what "wherever the two agree" means:
    // their recorded offset indexes the original input, so the gem's number and
    // the port's are directly comparable. A shifted case's recorded offset
    // indexes `preprocessed` instead and is not comparable here — that it MOVED
    // is asserted in "genuinely exercises the mapping" below, and the port's
    // actual `ParseError.index` is pinned per case by the block above, shifted
    // or not.
    //
    // An earlier version looped over every case and, for the shifted ones,
    // compared `MAPPED_INDEX.get(id)` to itself. That branch could not fail,
    // while the comment above it claimed it was the one that would.
    const comparable = rejections.filter(
      (entry) => entry.input === entry.preprocessed && entry.id !== KNOWN_POSITION_DIVERGENCE,
    );
    expect(comparable.length).toBeGreaterThan(0);
    for (const entry of comparable) {
      expect(MAPPED_INDEX.get(entry.id), entry.id).toBe(entry.index);
    }
  });

  it("genuinely exercises the mapping, and does not merely restate the corpus", () => {
    // Without a case whose preprocessing changes length, every assertion above
    // is satisfied by a port that ignores its offset map completely.
    const shifted = rejections.filter((entry) => entry.input !== entry.preprocessed);
    expect(shifted.length).toBeGreaterThan(0);
    for (const entry of shifted) {
      expect(MAPPED_INDEX.get(entry.id), entry.id).not.toBe(entry.index);
    }
  });
});

describe("the recorded offset describes the recorded text", () => {
  it("points inside `preprocessed`, which is what it is an offset into", () => {
    for (const entry of rejections) {
      if (entry.index === undefined) continue;
      expect(entry.index, entry.id).toBeGreaterThanOrEqual(0);
      expect(entry.index, entry.id).toBeLessThanOrEqual(entry.preprocessed.length);
    }
  });

  it("is present on every case, and not all zero", () => {
    // All-zero would be the signature of reading Parslet's root failure
    // position, which is 0 for every rejection whatever went wrong deeper in.
    const indices = rejections.map((entry) => entry.index);
    expect(indices.every((index) => index !== undefined)).toBe(true);
    expect(new Set(indices).size).toBeGreaterThan(1);
  });
});
