/**
 * The gem-verified render sweep: 1,642 inputs fed to the ORACLE
 * (`Plurimath::Math.parse(input, :asciimath).to_asciimath` on the pinned
 * checkout, plurimath 0.11.6 at 00c52783, 2026-08-06 — the one-off probe is
 * described below), each recorded as either the gem's exact bytes or its
 * refusal. This port must reproduce every pair.
 *
 * Composition of `render-sweep.json`:
 *
 *   - ~230 curated construct inputs: every `get_class` name the transform
 *     can reach in realistic forms, all fifty font keywords, tables in every
 *     bracket form, sub/sup shapes, fractions, text, color, mod, left/right,
 *     comma-in-table contexts, and the truncated-but-accepted shapes from
 *     the failure sweep (`x^`, `(a`, `frac(a`, ...);
 *   - 1,415 single-symbol inputs — one representative plain token per symbol
 *     id from the generated input table, which cross-checks the entire
 *     `ASCIIMATH_SYMBOLS` render table end to end;
 *   - the quoted `"P{...}"` wrapper forms that have no plain token.
 *
 * Six refusals are data, not test bugs, and are pinned as such: `x/` fails
 * to PARSE (unsatisfied frac), while `""`, `" "`, `textbf x`, `textit x`
 * and `textrm x` parse and then fail to RENDER — the gem's own parse puts a
 * bare string (or a `Text` holding a Symbol) into the tree, and
 * `to_asciimath` raises. The port answers `ParseError` and `RenderError`
 * respectively.
 *
 * The fixture is one-off generated, not regenerated by `scripts/`: like the
 * failure sweep in `failure-parity.spec.ts`, it records oracle answers that
 * only change when the pinned oracle moves.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { ParseError, RenderError } from "../../../src/core/errors";
import { parseAsciimath } from "../../../src/formats/asciimath/parser";
import { toAsciimath } from "../../../src/formats/asciimath/renderer";

interface SweepCase {
  readonly input: string;
  readonly render?: string;
  readonly error?: "parse" | "render";
  readonly errorClass?: string;
}

interface SweepFixture {
  readonly description: string;
  readonly oracle: { readonly version: string; readonly commit: string };
  readonly count: number;
  readonly cases: readonly SweepCase[];
}

const fixturePath = join(dirname(fileURLToPath(import.meta.url)), "render-sweep.json");
const fixture = JSON.parse(readFileSync(fixturePath, "utf8")) as SweepFixture;

describe("the gem-verified render sweep", () => {
  it("is complete and non-empty (an empty sweep is a failure, not a pass)", () => {
    expect(fixture.cases.length).toBe(1642);
    expect(fixture.cases.length).toBe(fixture.count);
    expect(fixture.oracle.commit).toBe("00c52783877b38f6b8e6e109f1803f96bb34fc62");
    for (const entry of fixture.cases) {
      // Exactly one of: a recorded render, or a recorded refusal.
      expect(typeof entry.input, JSON.stringify(entry)).toBe("string");
      expect(entry.render !== undefined || entry.error !== undefined).toBe(true);
      expect(entry.render !== undefined && entry.error !== undefined).toBe(false);
    }
  });

  it("reproduces every gem render byte for byte", () => {
    const rendered = fixture.cases.filter((entry) => entry.render !== undefined);
    expect(rendered.length).toBeGreaterThan(0);
    const divergences: string[] = [];
    for (const entry of rendered) {
      let actual: string;
      try {
        actual = toAsciimath(parseAsciimath(entry.input));
      } catch (error) {
        divergences.push(`${JSON.stringify(entry.input)}: threw ${String(error)}`);
        continue;
      }
      if (actual !== entry.render) {
        divergences.push(
          `${JSON.stringify(entry.input)}: rendered ${JSON.stringify(actual)}, gem says ${JSON.stringify(entry.render)}`,
        );
      }
    }
    expect(divergences).toEqual([]);
    expect(rendered.length).toBe(1636);
  });

  it("refuses to parse exactly what the gem refuses to parse", () => {
    const refused = fixture.cases.filter((entry) => entry.error === "parse");
    expect(refused.length).toBe(1);
    for (const entry of refused) {
      expect(() => parseAsciimath(entry.input), JSON.stringify(entry.input)).toThrow(ParseError);
    }
  });

  it("raises RenderError exactly where the gem's render raises", () => {
    const refused = fixture.cases.filter((entry) => entry.error === "render");
    expect(refused.length).toBe(5);
    for (const entry of refused) {
      const formula = parseAsciimath(entry.input); // the gem parses these too
      expect(() => toAsciimath(formula), JSON.stringify(entry.input)).toThrow(RenderError);
    }
  });
});
