/**
 * Negative parity for LaTeX: the port refuses what the gem refuses.
 *
 * The sibling of `test/formats/asciimath/rejection-parity.spec.ts`, and it
 * exists for the same reason. The positive corpus records only what the gem
 * *produces*, so a port that returns something plausible wherever the gem
 * raises passes every case in `corpus/latex/*.yaml` and is still wrong.
 *
 * These cases come from the shared corpus (`plurimath-corpus/rejections/1`,
 * `corpus/latex/rejections.yaml`), generated by sweeping candidate inputs
 * against the oracle and keeping the ones it refused. They arrived with the pin
 * that added the LaTeX rejection corpus, and they are the first rejection cases
 * this repository has in any notation other than AsciiMath. Nothing checked them
 * before this file: the AsciiMath suite read the rejection corpus unscoped, fed
 * `\frac{1` to `parseAsciimath` — which accepts it, since it is a legal
 * AsciiMath expression — and reported a refusal failure against a parser that
 * was never asked the question.
 *
 * On the recorded offset: `error.index` is an offset into `preprocessed`, not
 * into `input`. LaTeX's preprocessing pass strips whitespace and rewrites
 * entities (`src/formats/latex/preprocess.ts`), so every later offset shifts.
 * The port's own `ParseError.index` is an offset into the ORIGINAL input
 * (ARCHITECTURE.md §5). The two are comparable only through the `SourceMap`
 * that same pass returns, and that map is what this file compares through —
 * rather than a hand-written table of expected numbers, which would prove
 * nothing about the mapping itself.
 */

import { describe, expect, it } from "vitest";
import type { ParseError } from "../../../src/core/errors";
import { parseLatex } from "../../../src/formats/latex/parser";
import { preprocess } from "../../../src/formats/latex/preprocess";
import { loadPinnedCorpus, type PinnedRejection } from "../../core/corpus-pin";
import { casesInInputFormat } from "../../core/model-builder";

const corpus = loadPinnedCorpus();

/**
 * The LaTeX rejections, selected on the case's own `input_format` through the
 * shared selector rather than a filter written out here — the same one
 * `parseableCases` uses for AsciiMath, so the two suites cannot drift into
 * disagreeing about what "the cases this parser may be given" means. It throws
 * on an empty match, so a pin that drops `corpus/latex/rejections.yaml` fails
 * this file instead of quietly running zero cases.
 */
const rejections: readonly PinnedRejection[] = casesInInputFormat(corpus.rejections, "latex");

describe("the LaTeX rejection corpus", () => {
  it("is not empty, asserted as a count", () => {
    expect(rejections.length).toBeGreaterThan(0);
    expect(rejections.length).toBe(14);
  });

  it("names every case exactly once", () => {
    expect(new Set(rejections.map((entry) => entry.id)).size).toBe(rejections.length);
  });

  it("is all LaTeX, and all one category", () => {
    for (const entry of rejections) {
      expect(entry.inputFormat, entry.id).toBe("latex");
      expect(entry.category, entry.id).toBe("parse_error");
    }
  });
});

describe("every recorded LaTeX rejection is refused here too", () => {
  it.each(rejections.map((entry) => [entry.id, entry] as const))("%s", (_id, entry) => {
    let caught: unknown;
    try {
      parseLatex(entry.input);
    } catch (error) {
      caught = error;
    }

    // Two assertions doing two different jobs. The first only has to prove
    // something was thrown, and names the input when nothing was — the failure
    // that matters here is an input the gem refuses and this port ACCEPTS.
    expect(caught, `${entry.id}: ${JSON.stringify(entry.input)} was accepted`).toBeInstanceOf(
      Error,
    );
    // The discrimination is `code`, never `instanceof ParseError`: a dual
    // ESM/CJS load can hold two copies of these classes and `instanceof` across
    // copies is false (ARCHITECTURE.md §5).
    expect((caught as ParseError).code, entry.id).toBe("PARSE_ERROR");
  });
});

/**
 * The two cases where the port's failure position does not reproduce the gem's,
 * recorded rather than hidden. Both are the same shape:
 *
 *   latex-right-without-left  `x \right)`       gem→3 (`r` of `right`), port 2 (`\`)
 *   latex-end-without-begin   `a \end{matrix}`  gem→3 (`e` of `end`),   port 2 (`\`)
 *
 * Both readings of "where it failed" are defensible — Parslet reports the
 * furthest position any branch reached, which lands one character into the
 * command name, while the port reports where the unsatisfiable construct began,
 * which is its backslash — but they are not the same number. This is the same
 * divergence the AsciiMath suite pins for `right-unclosed`, and
 * PORTING-STANDARDS.md makes the gem's number the specification, so it is
 * recorded here with its measured values rather than asserted away.
 */
const KNOWN_POSITION_DIVERGENCES: readonly string[] = [
  "latex-end-without-begin",
  "latex-right-without-left",
];

/** What the port actually reports, per case, measured against this pin. */
const PORT_INDEX: ReadonlyMap<string, number> = new Map([
  ["latex-unclosed-brace", 7],
  ["latex-stray-close-brace", 1],
  ["latex-unknown-command", 1],
  ["latex-frac-no-args", 5],
  ["latex-frac-one-arg", 8],
  ["latex-right-without-left", 2],
  ["latex-begin-without-end", 16],
  ["latex-end-without-begin", 2],
  ["latex-whitespace-only", 3],
  ["latex-lone-backslash", 1],
  ["latex-unclosed-text", 9],
  ["latex-nested-unclosed", 17],
  ["latex-command-bad-chars", 1],
  ["latex-tilde", 1],
]);

describe("the port maps the LaTeX failure position back to the original input", () => {
  it("covers every recorded rejection, so a new case cannot skip the check", () => {
    expect([...PORT_INDEX.keys()].sort()).toStrictEqual(rejections.map((entry) => entry.id).sort());
  });

  it("reproduces the gem's preprocessing byte for byte", () => {
    // The comparison below maps the gem's offset through THIS port's source
    // map. That is only meaningful if the two passes produced the same text: a
    // port whose preprocessing differed could map an offset through a map of a
    // different string and still land somewhere plausible.
    for (const entry of rejections) {
      expect(preprocess(entry.input).text, entry.id).toBe(entry.preprocessed);
    }
  });

  it("the counts this file names are derived, not recited", () => {
    // 10 unshifted / 4 shifted / 12 of 14 agreeing, computed from the corpus
    // and the map rather than restated from the prose above.
    const unshifted = rejections.filter((entry) => entry.input === entry.preprocessed);
    const shifted = rejections.filter((entry) => entry.input !== entry.preprocessed);
    expect(unshifted.length).toBe(10);
    expect(shifted.length).toBe(4);

    const diverging = rejections.filter(
      (entry) => mappedGemIndex(entry) !== PORT_INDEX.get(entry.id),
    );
    expect(diverging.map((entry) => entry.id).sort()).toStrictEqual([
      ...KNOWN_POSITION_DIVERGENCES,
    ]);
    expect(rejections.length - diverging.length).toBe(12);
  });

  it.each(rejections.map((entry) => [entry.id, entry] as const))(
    "%s: reports the measured original-input offset",
    (id, entry) => {
      let caught: unknown;
      try {
        parseLatex(entry.input);
      } catch (error) {
        caught = error;
      }
      expect(caught, `${id} was accepted`).toBeInstanceOf(Error);
      expect((caught as ParseError).index, id).toBe(PORT_INDEX.get(id));
    },
  );

  it("reproduces the gem's recorded offset wherever the two agree", () => {
    // Every case except the two pinned divergences, mapped through the port's
    // own source map. This is the assertion that would break if the port
    // stopped mapping offsets at all.
    const comparable = rejections.filter((entry) => !KNOWN_POSITION_DIVERGENCES.includes(entry.id));
    expect(comparable.length).toBe(12);
    for (const entry of comparable) {
      expect(PORT_INDEX.get(entry.id), entry.id).toBe(mappedGemIndex(entry));
    }
  });

  it("genuinely exercises the mapping, and does not merely restate the corpus", () => {
    // Without a case whose preprocessing changes length, every assertion above
    // is satisfied by a port that ignores its source map completely. Four such
    // cases exist, and for each the mapped offset MOVED.
    const shifted = rejections.filter((entry) => entry.input !== entry.preprocessed);
    expect(shifted.length).toBeGreaterThan(0);
    for (const entry of shifted) {
      expect(mappedGemIndex(entry), entry.id).not.toBe(entry.index);
    }
  });
});

describe("the recorded offset describes the recorded text", () => {
  it("points inside `preprocessed`, which is what it is an offset into", () => {
    for (const entry of rejections) {
      if (entry.index === undefined) continue;
      expect(entry.index, entry.id).toBeGreaterThanOrEqual(0);
      expect(entry.index, entry.id).toBeLessThanOrEqual(entry.preprocessed.length);
    }
  });

  it("is present on every case, and not all zero", () => {
    const indices = rejections.map((entry) => entry.index);
    expect(indices.every((index) => index !== undefined)).toBe(true);
    expect(new Set(indices).size).toBeGreaterThan(1);
  });
});

/** The gem's recorded offset, carried into the original input's coordinates. */
function mappedGemIndex(entry: PinnedRejection): number {
  if (entry.index === undefined) throw new Error(`${entry.id} has no recorded index`);
  return preprocess(entry.input).map.toOriginal(entry.index);
}
