/**
 * The gem-verified LaTeX render sweep: the SAME 1,642 inputs as the
 * asciimath sweep (`../asciimath/render-sweep.json` — curated constructs,
 * one representative token per symbol id, and the quoted `"P{…}"` wrappers),
 * re-fed to the ORACLE as `Plurimath::Math.parse(input, :asciimath).to_latex`
 * on the pinned checkout (plurimath 0.11.6 at 00c52783, 2026-08-06), each
 * recorded as either the gem's exact bytes or its refusal. This port must
 * reproduce every pair.
 *
 * The refusal set is identical to the asciimath sweep's: `x/` fails to
 * PARSE (unsatisfied frac), while `""`, `" "`, `textbf x`, `textit x` and
 * `textrm x` parse and then fail to RENDER — the gem's own parse puts a bare
 * string (or a `Text` holding a Symbol) into the tree, and `to_latex` raises
 * (wrapped into `Math::ParseError` at its formula boundary). The port
 * answers `ParseError` and `RenderError` respectively.
 *
 * The fixture is one-off generated, not regenerated by `scripts/`: like the
 * failure sweep in `../asciimath/failure-parity.spec.ts`, it records oracle
 * answers that only change when the pinned oracle moves.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { ParseError, RenderError } from "../../../src/core/errors";
import { parseAsciimath } from "../../../src/formats/asciimath/parser";
import { toLatex } from "../../../src/formats/latex/renderer";

interface SweepCase {
  readonly input: string;
  readonly render?: string;
  readonly error?: "parse" | "render";
  readonly errorClass?: string;
}

interface SweepFixture {
  readonly description: string;
  readonly oracle: { readonly version: string; readonly commit: string };
  readonly count: number;
  readonly cases: readonly SweepCase[];
}

const fixturePath = join(dirname(fileURLToPath(import.meta.url)), "render-sweep.json");
const fixture = JSON.parse(readFileSync(fixturePath, "utf8")) as SweepFixture;

describe("the gem-verified latex render sweep", () => {
  it("is complete and non-empty (an empty sweep is a failure, not a pass)", () => {
    expect(fixture.cases.length).toBe(1642);
    expect(fixture.cases.length).toBe(fixture.count);
    expect(fixture.oracle.commit).toBe("00c52783877b38f6b8e6e109f1803f96bb34fc62");
    for (const entry of fixture.cases) {
      // Exactly one of: a recorded render, or a recorded refusal.
      expect(typeof entry.input, JSON.stringify(entry)).toBe("string");
      expect(entry.render !== undefined || entry.error !== undefined).toBe(true);
      expect(entry.render !== undefined && entry.error !== undefined).toBe(false);
    }
  });

  // 30s, not the 5s default. This walks the whole recorded sweep — thousands
  // of parses and renders — and lands within a few hundred milliseconds of the
  // default when the suite runs it alongside everything else, so it passed
  // alone and failed in a full run. A timeout that depends on machine load is
  // a flaky gate, and a flaky gate gets ignored.
  it("reproduces every gem render byte for byte", () => {
    const rendered = fixture.cases.filter((entry) => entry.render !== undefined);
    expect(rendered.length).toBeGreaterThan(0);
    const divergences: string[] = [];
    for (const entry of rendered) {
      let actual: string;
      try {
        actual = toLatex(parseAsciimath(entry.input));
      } catch (error) {
        divergences.push(`${JSON.stringify(entry.input)}: threw ${String(error)}`);
        continue;
      }
      if (actual !== entry.render) {
        divergences.push(
          `${JSON.stringify(entry.input)}: rendered ${JSON.stringify(actual)}, gem says ${JSON.stringify(entry.render)}`,
        );
      }
    }
    expect(divergences).toEqual([]);
    expect(rendered.length).toBe(1636);
  }, 30_000);

  it("refuses to parse exactly what the gem refuses to parse", () => {
    const refused = fixture.cases.filter((entry) => entry.error === "parse");
    expect(refused.length).toBe(1);
    for (const entry of refused) {
      expect(() => parseAsciimath(entry.input), JSON.stringify(entry.input)).toThrow(ParseError);
    }
  });

  it("raises RenderError exactly where the gem's render raises", () => {
    const refused = fixture.cases.filter((entry) => entry.error === "render");
    expect(refused.length).toBe(5);
    for (const entry of refused) {
      const formula = parseAsciimath(entry.input); // the gem parses these too
      expect(() => toLatex(formula), JSON.stringify(entry.input)).toThrow(RenderError);
    }
  });
});
