#!/usr/bin/env ruby
# frozen_string_literal: true

# Emits oracle expectations for the formats the shared corpus does not carry
# targets for (today: omml, html), so those renderers get the same executable
# parity coverage the four P1 formats already have.
#
#   ruby scripts/generate-parity-fixtures.rb --oracle <path> --out test/formats
#
# The oracle path MUST be a clean checkout of the pinned plurimath commit.
# This script loads it through $LOAD_PATH and refuses to run against an
# installed gem, because that silently answers from a different version --
# a trap that has cost this project real time (PORTING-STANDARDS.md).

require "json"
require "optparse"
require "yaml"

FORMATS = %w[omml html].freeze

options = { oracle: nil, out: "test/formats", corpus: "submodules/plurimath-testsuite/corpus/asciimath" }
OptionParser.new do |o|
  o.on("--oracle PATH", "clean pinned plurimath checkout") { |v| options[:oracle] = v }
  o.on("--out PATH", "output root (default test/formats)") { |v| options[:out] = v }
  o.on("--corpus PATH", "corpus dir") { |v| options[:corpus] = v }
end.parse!

abort "--oracle is required" unless options[:oracle]
oracle = File.expand_path(options[:oracle])
lib = File.join(oracle, "lib")
abort "not a plurimath checkout: #{lib}" unless File.directory?(lib) && File.exist?(File.join(lib, "plurimath.rb"))

$LOAD_PATH.unshift(lib)
require "plurimath"
require "plurimath/version"

loaded = $LOADED_FEATURES.grep(%r{/plurimath\.rb\z}).first
unless loaded&.start_with?(lib)
  abort "REFUSING: loaded #{loaded.inspect}, not the pinned checkout at #{lib}. " \
        "An installed gem answers from a different version."
end

def oracle_commit(oracle)
  sha = `git -C #{oracle.shellescape} rev-parse HEAD 2>/dev/null`.strip
  dirty = !`git -C #{oracle.shellescape} status --porcelain 2>/dev/null`.strip.empty?
  abort "REFUSING: oracle checkout is dirty. Expectations must come from a clean tree." if dirty
  sha
end
require "shellwords"

cases = []
Dir.glob(File.join(options[:corpus], "**", "*.yaml")).sort.each do |path|
  next if File.basename(path) == "provenance.yaml"

  doc = YAML.safe_load_file(path, permitted_classes: [], aliases: true)
  next unless doc.is_a?(Hash) && doc["cases"]

  doc["cases"].each do |c|
    next unless c.is_a?(Hash) && c["input"].is_a?(String)

    cases << { group: doc["group"], id: c["id"], input: c["input"] }
  end
end
abort "REFUSING: zero corpus cases found under #{options[:corpus]}" if cases.empty?

commit = oracle_commit(oracle)

FORMATS.each do |format|
  rows = cases.map do |c|
    row = { "group" => c[:group], "id" => c[:id], "input" => c[:input] }
    begin
      formula = Plurimath::Math.parse(c[:input], :asciimath)
      row["expected"] = formula.public_send("to_#{format}")
    rescue StandardError => e
      row["raises"] = e.class.name
    end
    row
  end

  rendered = rows.count { |r| r.key?("expected") }
  abort "REFUSING: #{format} produced zero rendered cases" if rendered.zero?

  payload = {
    "$comment" => "GENERATED by scripts/generate-parity-fixtures.rb. Do not edit.",
    "oracle" => { "commit" => commit, "version" => (defined?(Plurimath::VERSION) ? Plurimath::VERSION : "unknown") },
    "format" => format,
    "caseCount" => rows.length,
    "renderedCount" => rendered,
    "cases" => rows,
  }
  dir = File.join(options[:out], format)
  Dir.mkdir(dir) unless File.directory?(dir)
  out = File.join(dir, "parity-fixtures.json")
  File.write(out, "#{JSON.pretty_generate(payload)}\n")
  puts "#{format}: #{rows.length} cases, #{rendered} rendered -> #{out}"
end
