#!/usr/bin/env ruby
# frozen_string_literal: true

# Sweeps every declared node kind against the DEGENERATE values its slots can
# hold -- nil, false, 0, "", [] -- and records what the gem does.
#
#   ruby scripts/probe-degenerate-slots.rb --oracle <clean pinned checkout> \
#        --out test/formats/<format>/degenerate-fixtures.json --format omml
#
# Why this exists: every parity defect found in the OMML review lived in a
# degenerate or optional slot the conformance corpus never constructs, and
# ARCHITECTURE.md section 5 states hand-built trees are a SUPPORTED use. Five of
# eight shared one root cause -- Ruby-falsy is {nil,false}, JavaScript-falsy also
# swallows 0 and "". A sweep finds those; example-based fixtures do not.

require "json"
require "optparse"
require "shellwords"

options = { oracle: nil, out: nil, format: "omml" }
OptionParser.new do |o|
  o.on("--oracle PATH") { |v| options[:oracle] = v }
  o.on("--out PATH")    { |v| options[:out] = v }
  o.on("--format NAME") { |v| options[:format] = v }
end.parse!
abort "--oracle and --out are required" unless options[:oracle] && options[:out]

oracle = File.expand_path(options[:oracle])
lib = File.join(oracle, "lib")
abort "not a plurimath checkout: #{lib}" unless File.exist?(File.join(lib, "plurimath.rb"))
$LOAD_PATH.unshift(lib)
require "plurimath"
loaded = $LOADED_FEATURES.grep(%r{/plurimath\.rb\z}).first
abort "REFUSING: loaded #{loaded.inspect}, not #{lib}" unless loaded&.start_with?(lib)
abort "REFUSING: oracle checkout is dirty" unless `git -C #{oracle.shellescape} status --porcelain`.strip.empty?

S = Plurimath::Math::Symbols::Symbol
FN = Plurimath::Math::Function

# The degenerate values. `false`, `0` and `""` are the ones that separate
# Ruby-falsy from JavaScript-falsy; nil and [] separate present from absent.
DEGENERATE = {
  "nil" => nil, "false" => false, "true" => true,
  "zero" => 0, "empty-string" => "", "empty-array" => [],
  "node" => :NODE,
}.freeze

# kind => [ruby class, arity of positional node slots, takes options/attributes]
KINDS = {
  "frac"        => [FN::Frac, 2, nil],
  "base"        => [FN::Base, 2, nil],
  "power"       => [FN::Power, 2, nil],
  "nary"        => [FN::Nary, 4, nil],
  "obrace"      => [FN::Obrace, 1, :attributes],
  "ubrace"      => [FN::Ubrace, 1, :attributes],
  "bar"         => [FN::Bar, 1, :attributes],
  "hat"         => [FN::Hat, 1, :attributes],
  "dot"         => [FN::Dot, 1, :attributes],
  "ddot"        => [FN::Ddot, 1, :attributes],
  "tilde"       => [FN::Tilde, 1, :attributes],
  "vec"         => [FN::Vec, 1, :attributes],
  "ul"          => [FN::Ul, 1, :attributes],
  "abs"         => [FN::Abs, 1, nil],
  "ceil"        => [FN::Ceil, 1, nil],
  "floor"       => [FN::Floor, 1, nil],
  "norm"        => [FN::Norm, 1, nil],
  "sqrt"        => [FN::Sqrt, 1, nil],
  "overset"     => [FN::Overset, 2, :options],
  "underset"    => [FN::Underset, 2, :options],
}.freeze

def materialise(token) = token == :NODE ? S.new("a") : token

rows = []
KINDS.each do |kind, (klass, arity, bag)|
  (0...arity).each do |slot|
    DEGENERATE.each do |label, token|
      args = Array.new(arity) { S.new("a") }
      args[slot] = materialise(token)
      args << {} if bag
      row = { "kind" => kind, "slot" => slot, "value" => label }
      begin
        node = klass.new(*args)
        xml = Plurimath::Math::Formula.new([node]).public_send("to_#{options[:format]}")
        row["renders"] = true
        row["elements"] = xml.scan(/<m:([a-zA-Z]+)/).flatten.uniq.sort
      rescue StandardError => e
        row["renders"] = false
        row["error"] = e.class.name
      end
      rows << row
    end
  end
end
abort "REFUSING: zero rows probed" if rows.empty?

payload = {
  "$comment" => "GENERATED by scripts/probe-degenerate-slots.rb. Do not edit.",
  "oracle" => { "commit" => `git -C #{oracle.shellescape} rev-parse HEAD`.strip },
  "format" => options[:format],
  "rowCount" => rows.length,
  "rendersCount" => rows.count { |r| r["renders"] },
  "rows" => rows,
}
File.write(options[:out], "#{JSON.pretty_generate(payload)}\n")
puts "#{rows.length} rows (#{payload['rendersCount']} render) -> #{options[:out]}"
