# frozen_string_literal: true

# Shared provenance support for the per-format JSON fixture generators.
#
# `generate-corpus.rb` owns the repository's full ARCHITECTURE.md section 7
# provenance model. Reusing it here keeps the oracle, lockfile, runtime, XML
# engine, configuration, and dependency records identical. This file adds only
# the entrypoint/input hashes and the adjacent payload record specific to JSON
# renderer fixtures.

require "yaml"
require_relative "generate-corpus"

module RenderFixtureProvenance
  SUPPORT_PATH = "scripts/render-fixture-provenance.rb"
  MANAGED_PAYLOAD_BASENAMES = %w[
    degenerate-fixtures.json
    parity-fixtures.json
  ].freeze

  module_function

  def manifest_path(payload_path)
    unless payload_path.end_with?(".json")
      raise CorpusGenerator::Error, "fixture payload must end in .json: #{payload_path}"
    end

    payload_path.delete_suffix(".json") + ".manifest.yaml"
  end

  # The canonical parity and degenerate generators run one after the other from
  # the same clean source commit. After the first runs, its payload and sidecar
  # are dirty only because they are managed outputs; the second generator must
  # not mistake them for dirty source. Custom output names remain isolated to
  # their own payload and sidecar.
  def managed_output_paths(payload_path, repo_root: CorpusGenerator::REPO_ROOT)
    own_paths = [payload_path, manifest_path(payload_path)]
    return own_paths unless MANAGED_PAYLOAD_BASENAMES.include?(File.basename(payload_path))

    directory = File.dirname(File.expand_path(payload_path))
    managed_root = File.join(File.expand_path(repo_root), "test", "formats")
    canonical_directory = File.join(managed_root, File.basename(directory))
    return own_paths unless directory == canonical_directory

    MANAGED_PAYLOAD_BASENAMES.flat_map do |basename|
      managed_payload = File.join(directory, basename)
      [managed_payload, manifest_path(managed_payload)]
    end
  end

  def prepare(oracle:, payload_path:, generator_path:, allow_dirty:, corpus:, inventory: nil)
    sidecar_path = manifest_path(payload_path)
    CorpusGenerator.require_ox_engine!
    dirty = CorpusGenerator.check_checkouts!(
      oracle,
      oracle,
      managed_output_paths(payload_path),
      allow_dirty,
    )
    provenance = CorpusGenerator.build_provenance(oracle, dirty, allow_dirty)
    inputs = generator_inputs(generator_path)
    generator = {
      "path" => generator_path,
      "sha256" => inputs.fetch(generator_path),
      "inputs" => inputs,
      "repository" => provenance.fetch("generator").fetch("repository"),
    }
    generator["inventory"] = inventory_record(inventory) if inventory

    manifest = provenance.merge("generator" => generator)
    if corpus
      corpus_record = corpus_provenance
      corpus_dirty = corpus_record.fetch("repository").fetch("dirty_paths")
      unless corpus_dirty.empty?
        unless allow_dirty
          raise CorpusGenerator::Error,
                "Refusing to generate from dirty pinned corpus: #{corpus_dirty.join(', ')}"
        end
        manifest = manifest.merge(
          "committable" => false,
          "warnings" => manifest.fetch("warnings") +
            ["corpus checkout dirty: #{corpus_dirty.join(', ')}"],
        )
      end
      manifest["corpus"] = corpus_record
    end
    [sidecar_path, manifest]
  end

  def write_manifest(sidecar_path:, payload_path:, payload_schema:, payload_bytes:, provenance:)
    manifest = provenance.merge(
      "payload" => {
        "path" => File.basename(payload_path),
        "schema" => payload_schema,
        "sha256" => CorpusGenerator.sha256(payload_bytes),
        "bytes" => payload_bytes.bytesize,
      },
    )
    header = <<~HEADER
      # Sidecar provenance manifest. Generated by #{provenance.fetch('generator').fetch('path')}; do not edit.
      # `payload.sha256` covers the whole payload file, including its final newline.
    HEADER
    File.binwrite(sidecar_path, "#{header}#{CorpusGenerator.dump_yaml(manifest)}")
  end

  def generator_inputs(generator_path)
    [CorpusGenerator::GENERATOR_PATH, SUPPORT_PATH, generator_path].uniq.sort.to_h do |path|
      absolute = File.join(CorpusGenerator::REPO_ROOT, path)
      raise CorpusGenerator::Error, "generator input #{path} is missing" unless File.file?(absolute)

      [path, CorpusGenerator.sha256(File.binread(absolute))]
    end
  end

  # A generator may depend on a path inventory without reading file contents.
  # Record the exact sorted paths and hash their newline-delimited form; hashing
  # file bytes would create churn for edits that cannot affect oracle output.
  def inventory_record(inventory)
    glob = inventory.fetch("glob")
    paths = inventory.fetch("paths")
    unless glob.is_a?(String) && !glob.empty? && paths.is_a?(Array) &&
           paths.all? { |path| path.is_a?(String) && !path.empty? }
      raise CorpusGenerator::Error, "generator inventory must contain a glob and path strings"
    end
    unless paths == paths.sort && paths.uniq == paths
      raise CorpusGenerator::Error, "generator inventory paths must be sorted and unique"
    end

    {
      "glob" => glob,
      "paths" => paths,
      "sha256" => CorpusGenerator.sha256("#{paths.join("\n")}\n"),
    }
  end

  def corpus_provenance
    root = CorpusGenerator.pin_root
    provenance_relative = "corpus/provenance.yaml"
    provenance_path = File.join(root, provenance_relative)
    unless CorpusGenerator.git_repository?(root)
      raise CorpusGenerator::Error,
            "#{CorpusGenerator::PIN_RELATIVE_PATH} is not an initialized git checkout"
    end
    unless File.file?(provenance_path)
      raise CorpusGenerator::Error, "pinned corpus provenance is missing: #{provenance_path}"
    end

    bytes = File.binread(provenance_path)
    document = YAML.safe_load(bytes, aliases: false)
    schema = document.is_a?(Hash) ? document["schema"] : nil
    unless schema == CorpusGenerator::PIN_PROVENANCE_SCHEMA
      raise CorpusGenerator::Error,
            "#{provenance_path}: schema is #{schema.inspect}, expected " \
            "#{CorpusGenerator::PIN_PROVENANCE_SCHEMA.inspect}"
    end

    dirty = CorpusGenerator.dirty_paths(root)
    {
      "path" => CorpusGenerator::PIN_RELATIVE_PATH,
      "repository" => CorpusGenerator.checkout_provenance(root, dirty),
      "provenance" => {
        "path" => provenance_relative,
        "schema" => schema,
        "sha256" => CorpusGenerator.sha256(bytes),
      },
    }
  end
end
