/**
 * End-to-end output of the CLI's render options against the gem's bytes.
 *
 * Every expected string is `test/formats/cli/cli-fixtures.json`, generated by
 * `scripts/generate-cli-fixtures.rb` from the pinned gem, never typed: `cli`
 * rows are what the gem's own `plurimath convert` printed for the same long
 * flags, and `intent` rows are the gem's `to_mathml(display_style:, intent:
 * true)` (its command has no intent flag) printed with `puts`, as its
 * command prints every result.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it, vi } from "vitest";
import { EXIT_OK, EXIT_RUNTIME_ERROR, EXIT_USAGE_ERROR, run } from "../../src/cli/run";

const HERE = dirname(fileURLToPath(import.meta.url));

interface CliRow {
  readonly id: string;
  readonly via: "cli" | "api";
  readonly input: { readonly format: string; readonly text: string };
  readonly to: string;
  readonly options: {
    readonly displayStyle?: boolean;
    readonly splitOnLinebreak?: true;
    readonly mathRendering?: true;
    readonly intent?: true;
  };
  readonly expected: string;
}

const fixture = JSON.parse(
  readFileSync(join(HERE, "..", "formats", "cli", "cli-fixtures.json"), "utf8"),
) as { readonly schema: string; readonly caseCount: number; readonly cases: readonly CliRow[] };

function portArgv(row: CliRow): string[] {
  const argv = ["convert", "--from", row.input.format, "--to", row.to];
  if (row.options.displayStyle !== undefined) {
    argv.push("--display-style", String(row.options.displayStyle));
  }
  if (row.options.splitOnLinebreak === true) argv.push("--split-on-linebreak");
  if (row.options.mathRendering === true) argv.push("--math-rendering");
  if (row.options.intent === true) argv.push("--intent");
  return argv;
}

function fakeIo(stdin: string) {
  const out: string[] = [];
  const err: string[] = [];
  return {
    io: {
      readStdin: vi.fn(async () => stdin),
      readFile: vi.fn((): string => {
        throw new Error("no files in this spec");
      }),
      writeOut: vi.fn((text: string) => out.push(text)),
      writeErr: vi.fn((text: string) => err.push(text)),
    },
    out,
    err,
  };
}

describe("CLI render options match the gem", () => {
  it("reads the fixture it expects", () => {
    expect(fixture.schema).toBe("plurimath-corpus/cli/1");
    expect(fixture.cases.length).toBe(fixture.caseCount);
    expect(fixture.cases.length).toBeGreaterThan(0);
    // Each flag is exercised by at least one row.
    for (const key of ["displayStyle", "splitOnLinebreak", "mathRendering", "intent"]) {
      expect(fixture.cases.some((row) => key in row.options), key).toBe(true);
    }
  });

  it.each(fixture.cases.map((row) => [row.id, row] as const))("%s", async (_id, row) => {
    const { io, out, err } = fakeIo(row.input.text);
    const code = await run(portArgv(row), io);
    expect(err.join("")).toBe("");
    expect(code).toBe(EXIT_OK);
    expect(out.join("")).toBe(row.expected);
  });
});

describe("CLI render option errors", () => {
  it("exits 2 with usage on a bad --display-style value", async () => {
    const { io, out, err } = fakeIo("x");
    const code = await run(
      ["convert", "--from", "asciimath", "--to", "mathml", "--display-style", "no"],
      io,
    );
    expect(code).toBe(EXIT_USAGE_ERROR);
    expect(out).toEqual([]);
    expect(err.join("")).toMatch(/^plurimath: Invalid --display-style value "no"/);
    expect(io.readStdin).not.toHaveBeenCalled();
  });

  it("exits 2 on an unknown flag", async () => {
    const { io, err } = fakeIo("x");
    const code = await run(["convert", "--from", "asciimath", "--to", "mathml", "-s"], io);
    expect(code).toBe(EXIT_USAGE_ERROR);
    expect(err.join("")).toMatch(/^plurimath: Unknown option "-s"/);
  });

  it("exits 1 for --math-rendering with html output, which has no display tree", async () => {
    // The gem's command raises InvalidTypeError here too
    // (`Formula#to_display(:html)`).
    const { io, out, err } = fakeIo("x");
    const code = await run(
      ["convert", "--from", "asciimath", "--to", "html", "--math-rendering"],
      io,
    );
    expect(code).toBe(EXIT_RUNTIME_ERROR);
    expect(out).toEqual([]);
    expect(err.join("")).toMatch(/^plurimath: \[/);
  });
});
