/**
 * Oracle-backed parity for the kinds only the LaTeX, HTML and UnicodeMath
 * parsers (or a hand-built tree) can build: `Table` and its ten subclasses,
 * `Frac` carrying options, and `Nary` carrying options — OMML for all three,
 * MathML for `Nary`'s `options[:mask]`.
 *
 * The rows are the gem's own answers, generated by
 *   ruby scripts/generate-render-options-fixtures.rb --oracle <clean pinned checkout>
 * into `omml/` and `mathml/render-options-fixtures.json`, in four groups:
 *
 *   - `table-frac-nary-survey`: the inputs the three parsers produce that the
 *     renderers used to refuse (`TABLE_FRAC_NARY_TEXT_SOURCES`);
 *   - `table-frac-nary-spec`: every `ExpectedValues` constant the gem's
 *     `omml_spec.rb` renders that holds a Table, Nary or Frac;
 *   - `table-frac-nary-probe`: hand-built models, one per branch of
 *     `single_table?`, `nil_option?`, `fenced_table`, `fpr_element` and
 *     `chr_value`, including the shapes where the gem raises;
 *   - `nary-mask` (MathML): the four fillings of the two script slots against
 *     the masks that reach every branch of `Core#get_mask_options`.
 *
 * Every row is asserted: byte-for-byte where the gem renders, and where it
 * raised, a refusal of the same phase — a parse refusal is not a render
 * refusal, so a row the gem raised on while PARSING must fail to parse here and
 * one it raised on while RENDERING must parse and then fail to render.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { type MathNode, RenderError } from "../../src/core/index";
import { parseAsciimath } from "../../src/formats/asciimath/index";
import { parseHtml } from "../../src/formats/html/index";
import { parseLatex } from "../../src/formats/latex/index";
import { toMathml } from "../../src/formats/mathml/renderer";
import { toOmml } from "../../src/formats/omml/renderer";
import { parseUnicodemath } from "../../src/formats/unicodemath/index";
import { aliasIndex, buildNode, readCensus, type SerializedNode } from "../core/model-builder";

interface Row {
  readonly id: string;
  readonly group: string;
  readonly input: {
    readonly model?: SerializedNode;
    readonly format?: string;
    readonly text?: string;
  };
  readonly options: Readonly<Record<string, unknown>>;
  readonly expected?: string;
  readonly raises?: string;
  readonly raisedIn?: string;
}

interface Fixture {
  readonly cases: readonly Row[];
}

const HERE = dirname(fileURLToPath(import.meta.url));
const CENSUS_ALIASES = aliasIndex(readCensus());

function load(format: "mathml" | "omml"): Fixture {
  return JSON.parse(
    readFileSync(join(HERE, format, "render-options-fixtures.json"), "utf8"),
  ) as Fixture;
}

function build(row: Row): MathNode {
  if (row.input.model !== undefined) return buildNode(row.input.model, CENSUS_ALIASES);
  const text = row.input.text as string;
  switch (row.input.format) {
    case "asciimath":
      return parseAsciimath(text);
    case "latex":
      return parseLatex(text);
    case "html":
      return parseHtml(text);
    case "unicodemath":
      return parseUnicodemath(text);
    default:
      throw new Error(`${row.id}: unknown input format ${row.input.format}`);
  }
}

const GROUPS = {
  omml: ["table-frac-nary-survey", "table-frac-nary-spec", "table-frac-nary-probe"],
  mathml: ["nary-mask"],
} as const;

/** Rows measured at generation: [rendered by the gem, raised by the gem]. */
const MEASURED = { omml: [156, 2], mathml: [108, 22] } as const;

/**
 * Rows the gem renders and this port refuses, by id, each with the refusal it
 * must give. None of them is a Table, Frac or Nary refusal — those kinds render
 * every other row — so the message is pinned to name the kind that is not yet
 * ported, and a row that starts rendering fails until it is dropped here:
 *
 *   - 20 `ExpectedValues` models hold a `Text` whose `lang` is `omml`, which the
 *     `Text` renderer has not measured (`src/render/text/omml.ts`);
 *   - 2 hold an empty `Td`, deferred in `src/render/binary-function/omml.ts`;
 *   - 1 probe gives a Table a paren `Symbol` with a nil value, which the gem
 *     writes as an empty `m:begChr` and `symbolOmmlValue` refuses.
 */
const TEXT_LANG_OMML = /^Text lang "omml" has not been measured for OMML insertion/;
const EMPTY_TD = /^td\.parameterOne: the empty-cell branch is deferred/;
const PORT_REFUSES: Readonly<Record<string, ReadonlyMap<string, RegExp>>> = {
  omml: new Map<string, RegExp>([
    ...[
      "tfn-spec-ex_001",
      "tfn-spec-ex_045",
      "tfn-spec-ex_047",
      "tfn-spec-ex_049",
      "tfn-spec-ex_068",
      "tfn-spec-ex_069",
      "tfn-spec-ex_070",
      "tfn-spec-ex_071",
      "tfn-spec-ex_072",
      "tfn-spec-ex_133",
      "tfn-spec-ex_156",
      "tfn-spec-ex_157",
      "tfn-spec-ex_158",
      "tfn-spec-ex_159",
      "tfn-spec-ex_160",
      "tfn-spec-ex_161",
      "tfn-spec-ex_162",
      "tfn-spec-ex_176",
      "tfn-spec-ex_177",
      "tfn-spec-exissue158",
    ].map((id): [string, RegExp] => [id, TEXT_LANG_OMML]),
    ...["tfn-spec-ex_169", "tfn-spec-ex_171"].map((id): [string, RegExp] => [id, EMPTY_TD]),
    [
      "tfn-probe-table-nil-valued-paren",
      /^table\.openParen\.value: holds nil, not a measured string value/,
    ],
  ]),
  mathml: new Map<string, RegExp>(),
};

/** Rows the gem renders that the port renders byte-identically (a pin, not a knob). */
const MATCHING = { omml: 133, mathml: 108 } as const;

const RENDERERS = {
  mathml: (node: MathNode) => toMathml(node),
  omml: (node: MathNode) => toOmml(node),
} as const;

for (const format of ["omml", "mathml"] as const) {
  const groups: readonly string[] = GROUPS[format];
  const rows = load(format).cases.filter((row) => groups.includes(row.group));
  const rendered = rows.filter((row) => row.expected !== undefined);
  const raised = rows.filter((row) => row.raises !== undefined);
  const render = RENDERERS[format];
  const refuses = PORT_REFUSES[format] as ReadonlyMap<string, RegExp>;

  describe(`${format} table / frac / nary fixture`, () => {
    it("carries the measured rows, so the assertions below are not vacuous", () => {
      expect([rendered.length, raised.length]).toEqual(MEASURED[format]);
      expect(rows.length).toBe(rendered.length + raised.length);
      for (const group of groups) {
        expect(
          rows.some((row) => row.group === group),
          group,
        ).toBe(true);
      }
    });
  });

  describe(`${format} table / frac / nary parity, the rows the gem renders`, () => {
    it.each(rendered.map((row) => [row.id, row] as const))(
      "%s matches the gem byte-for-byte",
      (id, row) => {
        const refusal = refuses.get(id);
        if (refusal !== undefined) {
          expect(() => render(build(row))).toThrow(RenderError);
          expect(() => render(build(row))).toThrow(refusal);
          return;
        }
        expect(render(build(row))).toBe(row.expected);
      },
    );

    it("names only rows the gem renders, and leaves the rest matching", () => {
      const renderedIds = new Set(rendered.map((row) => row.id));
      expect([...refuses.keys()].filter((id) => !renderedIds.has(id))).toEqual([]);
      expect(rendered.length - refuses.size).toBe(MATCHING[format]);
    });
  });

  describe(`${format} table / frac / nary parity, the rows the gem refuses`, () => {
    it.each(raised.map((row) => [row.id, row] as const))(
      "%s is refused in the same phase",
      (_id, row) => {
        if (row.raisedIn === "parse") {
          expect(() => build(row)).toThrow();
          return;
        }
        const node = build(row);
        expect(() => render(node)).toThrow(RenderError);
      },
    );
  });
}
