/**
 * Oracle-backed parity for the kinds only the LaTeX, HTML and UnicodeMath
 * parsers (or a hand-built tree) can build: `Table` and its ten subclasses,
 * `Frac` carrying options, and `Nary` carrying options — OMML for all three,
 * MathML for `Nary`'s `options[:mask]`.
 *
 * The rows are the gem's own answers, generated by
 *   ruby scripts/generate-render-options-fixtures.rb --oracle <clean pinned checkout>
 * into `omml/` and `mathml/render-options-fixtures.json`, in four groups:
 *
 *   - `table-frac-nary-survey`: the inputs the three parsers produce that the
 *     renderers used to refuse (`TABLE_FRAC_NARY_TEXT_SOURCES`);
 *   - `table-frac-nary-spec`: every `ExpectedValues` constant the gem's
 *     `omml_spec.rb` renders that holds a Table, Nary or Frac;
 *   - `table-frac-nary-probe`: hand-built models, one per branch of
 *     `single_table?`, `nil_option?`, `fenced_table`, `fpr_element` and
 *     `chr_value`, including the shapes where the gem raises;
 *   - `nary-mask` (MathML): the four fillings of the two script slots against
 *     the masks that reach every branch of `Core#get_mask_options`.
 *
 * Every row is asserted: byte-for-byte where the gem renders, and where it
 * raised, a refusal of the same phase — a parse refusal is not a render
 * refusal, so a row the gem raised on while PARSING must fail to parse here and
 * one it raised on while RENDERING must parse and then fail to render.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { type MathNode, RenderError } from "../../src/core/index";
import { parseAsciimath } from "../../src/formats/asciimath/index";
import { parseHtml } from "../../src/formats/html/index";
import { parseLatex } from "../../src/formats/latex/index";
import { toMathml } from "../../src/formats/mathml/renderer";
import { toOmml } from "../../src/formats/omml/renderer";
import { parseUnicodemath } from "../../src/formats/unicodemath/index";
import { aliasIndex, buildNode, readCensus, type SerializedNode } from "../core/model-builder";

interface Row {
  readonly id: string;
  readonly group: string;
  readonly input: {
    readonly model?: SerializedNode;
    readonly format?: string;
    readonly text?: string;
  };
  readonly options: Readonly<Record<string, unknown>>;
  readonly expected?: string;
  readonly raises?: string;
  readonly raisedIn?: string;
}

interface Fixture {
  readonly cases: readonly Row[];
}

const HERE = dirname(fileURLToPath(import.meta.url));
const CENSUS_ALIASES = aliasIndex(readCensus());

function load(format: "mathml" | "omml"): Fixture {
  return JSON.parse(
    readFileSync(join(HERE, format, "render-options-fixtures.json"), "utf8"),
  ) as Fixture;
}

function build(row: Row): MathNode {
  if (row.input.model !== undefined) return buildNode(row.input.model, CENSUS_ALIASES);
  const text = row.input.text as string;
  switch (row.input.format) {
    case "asciimath":
      return parseAsciimath(text);
    case "latex":
      return parseLatex(text);
    case "html":
      return parseHtml(text);
    case "unicodemath":
      return parseUnicodemath(text);
    default:
      throw new Error(`${row.id}: unknown input format ${row.input.format}`);
  }
}

const GROUPS = {
  omml: ["table-frac-nary-survey", "table-frac-nary-spec", "table-frac-nary-probe"],
  mathml: ["nary-mask"],
} as const;

/** Rows measured at generation: [rendered by the gem, raised by the gem]. */
const MEASURED = { omml: [156, 2], mathml: [108, 22] } as const;

/**
 * Rows the gem renders that this port used to refuse — all three now render
 * byte-identically, so `PORT_REFUSES.omml` is empty:
 *
 *   - the 20 `ExpectedValues` models holding a `Text` whose `lang` is `omml`:
 *     `insert_t_tag` (text.rb:49-59) skips the `m:rPr/m:sty` wrapper for
 *     exactly that lang and adds it for every other lang including `nil`
 *     (measured on the oracle), and `src/render/text/omml.ts` now matches;
 *   - the 2 rows holding an empty `Td`: `Td#to_omml_without_math_tag`
 *     (td.rb:43-50) answers a bare `<m:e/>` before its content branch runs,
 *     and `src/render/binary-function/omml.ts` now matches;
 *   - the 1 probe giving a `Table` a paren `Symbol` with a nil value:
 *     `Table#paren` calls `to_omml_without_math_tag` directly, not `t_tag`,
 *     so a valueless base/abstract paren answers `nil` rather than raising,
 *     and the gem's attribute writer turns that into the empty string
 *     (`<m:begChr m:val=""/>`, measured) — `symbolOmmlValueOrNull` in
 *     `src/formats/omml/render-shared.ts` now matches.
 */
const PORT_REFUSES: Readonly<Record<string, ReadonlyMap<string, RegExp>>> = {
  omml: new Map<string, RegExp>(),
  mathml: new Map<string, RegExp>(),
};

/** Rows the gem renders that the port renders byte-identically (a pin, not a knob). */
const MATCHING = { omml: 156, mathml: 108 } as const;

const RENDERERS = {
  mathml: (node: MathNode) => toMathml(node),
  omml: (node: MathNode) => toOmml(node),
} as const;

for (const format of ["omml", "mathml"] as const) {
  const groups: readonly string[] = GROUPS[format];
  const rows = load(format).cases.filter((row) => groups.includes(row.group));
  const rendered = rows.filter((row) => row.expected !== undefined);
  const raised = rows.filter((row) => row.raises !== undefined);
  const render = RENDERERS[format];
  const refuses = PORT_REFUSES[format] as ReadonlyMap<string, RegExp>;

  describe(`${format} table / frac / nary fixture`, () => {
    it("carries the measured rows, so the assertions below are not vacuous", () => {
      expect([rendered.length, raised.length]).toEqual(MEASURED[format]);
      expect(rows.length).toBe(rendered.length + raised.length);
      for (const group of groups) {
        expect(
          rows.some((row) => row.group === group),
          group,
        ).toBe(true);
      }
    });
  });

  describe(`${format} table / frac / nary parity, the rows the gem renders`, () => {
    it.each(rendered.map((row) => [row.id, row] as const))(
      "%s matches the gem byte-for-byte",
      (id, row) => {
        const refusal = refuses.get(id);
        if (refusal !== undefined) {
          expect(() => render(build(row))).toThrow(RenderError);
          expect(() => render(build(row))).toThrow(refusal);
          return;
        }
        expect(render(build(row))).toBe(row.expected);
      },
    );

    it("names only rows the gem renders, and leaves the rest matching", () => {
      const renderedIds = new Set(rendered.map((row) => row.id));
      expect([...refuses.keys()].filter((id) => !renderedIds.has(id))).toEqual([]);
      expect(rendered.length - refuses.size).toBe(MATCHING[format]);
    });
  });

  describe(`${format} table / frac / nary parity, the rows the gem refuses`, () => {
    it.each(raised.map((row) => [row.id, row] as const))(
      "%s is refused in the same phase",
      (_id, row) => {
        if (row.raisedIn === "parse") {
          expect(() => build(row)).toThrow();
          return;
        }
        const node = build(row);
        expect(() => render(node)).toThrow(RenderError);
      },
    );
  });
}
